import { proposePatch } from './diagnose.js';

async function github(token, method, url, body) {
  const response = await fetch(`https://api.github.com${url}`, {
    method,
    headers: {
      Accept: 'application/vnd.github+json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json'
    },
    body: body ? JSON.stringify(body) : undefined
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(`GitHub ${method} ${url}: ${response.status} ${data.message ?? 'request failed'}`);
  return data;
}

async function sourceFile(token, repository, filePath, branch) {
  if (!/^[\w.-]+\/[\w.-]+$/.test(repository)) throw new Error('Invalid repository');
  if (!filePath || filePath.startsWith('/') || filePath.split('/').includes('..')) throw new Error('Invalid repository file path');
  const root = `/repos/${repository}`;
  const encodedPath = filePath.split('/').map(encodeURIComponent).join('/');
  const file = await github(token, 'GET', `${root}/contents/${encodedPath}${branch ? `?ref=${encodeURIComponent(branch)}` : ''}`);
  if (file.type !== 'file' || file.size > 100_000 || file.encoding !== 'base64') {
    throw new Error('Only source files under 100 KB are supported');
  }
  return { file, encodedPath, source: Buffer.from(file.content.replace(/\s/g, ''), 'base64').toString('utf8') };
}

export async function previewGitHubPatch({ token, repository, filePath, diagnosis }) {
  const { source } = await sourceFile(token, repository, filePath);
  return proposePatch(diagnosis, source, diagnosis.location?.line);
}

export async function createFixPullRequest({ token, repository, filePath, diagnosis, id }) {
  if (!token) throw new Error('GITHUB_TOKEN is required to create a pull request');
  const root = `/repos/${repository}`;
  const repo = await github(token, 'GET', root);
  const base = repo.default_branch;
  const { file, encodedPath, source } = await sourceFile(token, repository, filePath, base);
  const patch = proposePatch(diagnosis, source, diagnosis.location?.line);
  if (!patch) throw new Error('No safe automatic patch is available for this failure');

  const baseRef = await github(token, 'GET', `${root}/git/ref/heads/${encodeURIComponent(base)}`);
  const branch = `api-doctor/fix-${id}`;
  await github(token, 'POST', `${root}/git/refs`, {
    ref: `refs/heads/${branch}`,
    sha: baseRef.object.sha
  });
  await github(token, 'PUT', `${root}/contents/${encodedPath}`, {
    message: `fix: handle missing progress in demo API`,
    content: Buffer.from(patch.content, 'utf8').toString('base64'),
    sha: file.sha,
    branch
  });
  const pull = await github(token, 'POST', `${root}/pulls`, {
    title: `[API Doctor] ${diagnosis.title}`,
    head: branch,
    base,
    body: `## Observed failure\n\n${diagnosis.evidence}\n\n## Root cause\n\n${diagnosis.rootCause}\n\n## Proposed fix\n\n${patch.explanation}\n\nGenerated by API Doctor. Please review and run your API tests before merging.`,
    draft: true
  });
  return { url: pull.html_url, number: pull.number, patch };
}
