"""cards by serial number, pending actions, scan log

Revision ID: 5902bb4765f1
Revises: 8c27c7364569
Create Date: 2026-09-27 12:06:20.506094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5902bb4765f1'
down_revision: Union[str, Sequence[str], None] = '8c27c7364569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('terminal_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_scan_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('charge', 'redeem')", name=op.f('ck_pending_actions_kind')),
    sa.CheckConstraint("status IN ('pending', 'completed', 'cancelled')", name=op.f('ck_pending_actions_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pending_actions_created_by_users')),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], name=op.f('fk_pending_actions_terminal_id_terminals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_actions'))
    )
    op.create_index(op.f('ix_pending_actions_terminal_id'), 'pending_actions', ['terminal_id'], unique=False)
    op.create_index('uq_pending_actions_one_open', 'pending_actions', ['terminal_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('tag_scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('terminal_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('tag_uid', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('pending_action_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pending_action_id'], ['pending_actions.id'], name=op.f('fk_tag_scans_pending_action_id_pending_actions')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_tag_scans_student_id_users')),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], name=op.f('fk_tag_scans_terminal_id_terminals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_scans')),
    sa.UniqueConstraint('terminal_id', 'scan_id', name='uq_tag_scans_terminal_scan')
    )
    op.create_index(op.f('ix_tag_scans_tag_uid'), 'tag_scans', ['tag_uid'], unique=False)
    op.create_index(op.f('ix_tag_scans_terminal_id'), 'tag_scans', ['terminal_id'], unique=False)
    # Cards are now identified only by their serial number. Cards issued without one can't be used
    # any more: retire them (the placeholder only has to be unique among active cards, and they aren't).
    op.execute("UPDATE nfc_cards SET tag_uid = 'UNSET' || substr(md5(id::text), 1, 8), status = 'replaced' WHERE tag_uid IS NULL")
    op.alter_column('nfc_cards', 'tag_uid',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_constraint(op.f('uq_nfc_cards_card_token'), 'nfc_cards', type_='unique')
    op.create_index('uq_nfc_cards_active_uid', 'nfc_cards', ['tag_uid'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.drop_column('nfc_cards', 'card_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfc_cards', sa.Column('card_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.execute("UPDATE nfc_cards SET card_token = md5(random()::text || id::text)")
    op.alter_column('nfc_cards', 'card_token', existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_index('uq_nfc_cards_active_uid', table_name='nfc_cards', postgresql_where=sa.text("status = 'active'"))
    op.create_unique_constraint(op.f('uq_nfc_cards_card_token'), 'nfc_cards', ['card_token'], postgresql_nulls_not_distinct=False)
    op.alter_column('nfc_cards', 'tag_uid',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_index(op.f('ix_tag_scans_terminal_id'), table_name='tag_scans')
    op.drop_index(op.f('ix_tag_scans_tag_uid'), table_name='tag_scans')
    op.drop_table('tag_scans')
    op.drop_index('uq_pending_actions_one_open', table_name='pending_actions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_pending_actions_terminal_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    # ### end Alembic commands ###
