"""initial schema

Revision ID: 8c27c7364569
Revises: 
Create Date: 2026-09-27 10:45:39.559360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c27c7364569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_table('tts_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_tts_cache'))
    )
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('canteen', 'bookstore')", name=op.f('ck_merchants_kind')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_merchants_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index(op.f('ix_merchants_school_id'), 'merchants', ['school_id'], unique=False)
    op.create_table('reward_configs',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('value_paise', sa.BigInteger(), nullable=True),
    sa.Column('merchant_kind', sa.String(length=20), nullable=False),
    sa.CheckConstraint("type IN ('free_icecream', 'book_discount', 'olympiad_fee')", name=op.f('ck_reward_configs_type')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_reward_configs_school_id_schools')),
    sa.PrimaryKeyConstraint('school_id', 'rank', name=op.f('pk_reward_configs'))
    )
    op.create_table('terminals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('secret_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_terminals_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminals'))
    )
    op.create_index(op.f('ix_terminals_merchant_id'), 'terminals', ['merchant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'parent', 'admin', 'merchant_staff')", name=op.f('ck_users_role')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_users_merchant_id_merchants')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_users_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('image_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_lessons_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_content_hash'), 'lessons', ['content_hash'], unique=False)
    op.create_index(op.f('ix_lessons_student_id'), 'lessons', ['student_id'], unique=False)
    op.create_table('nfc_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('card_token', sa.String(length=64), nullable=False),
    sa.Column('tag_uid', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('daily_limit_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'blocked', 'lost', 'replaced')", name=op.f('ck_nfc_cards_status')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_nfc_cards_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nfc_cards')),
    sa.UniqueConstraint('card_token', name=op.f('uq_nfc_cards_card_token'))
    )
    op.create_index(op.f('ix_nfc_cards_student_id'), 'nfc_cards', ['student_id'], unique=False)
    op.create_index('uq_nfc_cards_one_active', 'nfc_cards', ['student_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('parent_students',
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_students_parent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_parent_students_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'student_id', name=op.f('pk_parent_students'))
    )
    op.create_table('points_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('iso_week', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_points_entries_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_points_entries_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points_entries'))
    )
    op.create_index(op.f('ix_points_entries_iso_week'), 'points_entries', ['iso_week'], unique=False)
    op.create_index(op.f('ix_points_entries_student_id'), 'points_entries', ['student_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('week', sa.String(length=8), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('value_paise', sa.BigInteger(), nullable=True),
    sa.Column('merchant_kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_terminal_id', sa.Uuid(), nullable=True),
    sa.Column('redeem_idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('issued', 'redeemed', 'expired')", name=op.f('ck_rewards_status')),
    sa.CheckConstraint("type IN ('free_icecream', 'book_discount', 'olympiad_fee')", name=op.f('ck_rewards_type')),
    sa.ForeignKeyConstraint(['redeemed_terminal_id'], ['terminals.id'], name=op.f('fk_rewards_redeemed_terminal_id_terminals')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_rewards_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_rewards_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewards')),
    sa.UniqueConstraint('redeem_idempotency_key', name=op.f('uq_rewards_redeem_idempotency_key')),
    sa.UniqueConstraint('school_id', 'week', 'rank', name='uq_rewards_school_week_rank')
    )
    op.create_index(op.f('ix_rewards_student_id'), 'rewards', ['student_id'], unique=False)
    op.create_table('students',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_students'))
    )
    op.create_table('terminal_nonces',
    sa.Column('terminal_id', sa.Uuid(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], name=op.f('fk_terminal_nonces_terminal_id_terminals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('terminal_id', 'nonce', name=op.f('pk_terminal_nonces'))
    )
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('balance_paise', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_paise >= 0', name=op.f('ck_wallets_non_negative')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_wallets_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('student_id', name=op.f('uq_wallets_student_id'))
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_paise', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('terminal_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('related_entry_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('topup', 'purchase', 'refund', 'adjustment')", name=op.f('ck_ledger_entries_type')),
    sa.ForeignKeyConstraint(['card_id'], ['nfc_cards.id'], name=op.f('fk_ledger_entries_card_id_nfc_cards')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_ledger_entries_merchant_id_merchants')),
    sa.ForeignKeyConstraint(['related_entry_id'], ['ledger_entries.id'], name=op.f('fk_ledger_entries_related_entry_id_ledger_entries')),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], name=op.f('fk_ledger_entries_terminal_id_terminals')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_ledger_entries_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_ledger_entries_idempotency_key'))
    )
    op.create_index(op.f('ix_ledger_entries_merchant_id'), 'ledger_entries', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    op.create_index('uq_ledger_entries_one_refund', 'ledger_entries', ['related_entry_id'], unique=True, postgresql_where=sa.text("type = 'refund'"))
    op.create_table('lesson_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_messages_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_messages'))
    )
    op.create_index(op.f('ix_lesson_messages_lesson_id'), 'lesson_messages', ['lesson_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_quizzes_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_quizzes_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_index(op.f('ix_quizzes_lesson_id'), 'quizzes', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_quizzes_student_id'), 'quizzes', ['student_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_attempts_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_quiz_attempts_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_student_id'), 'quiz_attempts', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_student_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quizzes_student_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_lesson_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_lesson_messages_lesson_id'), table_name='lesson_messages')
    op.drop_table('lesson_messages')
    op.drop_index('uq_ledger_entries_one_refund', table_name='ledger_entries', postgresql_where=sa.text("type = 'refund'"))
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_merchant_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('wallets')
    op.drop_table('terminal_nonces')
    op.drop_table('students')
    op.drop_index(op.f('ix_rewards_student_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_points_entries_student_id'), table_name='points_entries')
    op.drop_index(op.f('ix_points_entries_iso_week'), table_name='points_entries')
    op.drop_table('points_entries')
    op.drop_table('parent_students')
    op.drop_index('uq_nfc_cards_one_active', table_name='nfc_cards', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_nfc_cards_student_id'), table_name='nfc_cards')
    op.drop_table('nfc_cards')
    op.drop_index(op.f('ix_lessons_student_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_content_hash'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_terminals_merchant_id'), table_name='terminals')
    op.drop_table('terminals')
    op.drop_table('reward_configs')
    op.drop_index(op.f('ix_merchants_school_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('tts_cache')
    op.drop_table('schools')
    # ### end Alembic commands ###
